version: '3.3'

services:
  psql:
    image: 'bitnami/postgresql:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=dev
      - POSTGRESQL_DATABASE=dev